@startuml Plugin Manager Class Diagram

package plugin_manager <<Node>> #LightGreen {
    interface IPluginManager{
        + IPlugin* loadPlugin(const char* filename)
        + bool unloadPlugin(const char* filename)
        + IPlugin* getPlugin(const char* filename)
    }
    class PluginManager

    interface IPlugin{
        + const char* name()
    }

    ' Inheritance.
    PluginManager -|> IPluginManager
}

package app <<Node>> #LightBlue {
    class PluginA
    class PluginB{
    }
    interface ICustomPlugin{
        + void sayHelloTo( const char* username )
        + void doSomething()
    }
}

' Aggregation.
PluginManager o-- IPlugin : contains

' Dependency.
app -> IPlugin
app -> IPluginManager

' Inheritance.
PluginA -|> ICustomPlugin
ICustomPlugin -|> IPlugin
PluginB -|> IPlugin

@enduml
